authorName: pprp
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
#please use `nnictl ss_gen` to generate search space file first
searchSpacePath: "."
useAnnotation: False
tuner:
  codeDir: .
  classFileName: random_nas_tuner.py
  className: RandomNASTuner
trial:
  command: python3 train.py
  codeDir: .
  gpuNum: 0
